#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

./node_modules/.bin/pretty-quick --staged

if files=$(grep -rL Copyright src | grep -vi .json); then
  echo
  echo ❗Add copyright notice to the next files:
  echo "$files" | while read -r file; do
    echo " ‣ $file"
  done
  echo
  exit 1
fi
